spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    show-sql: ${JPA_SHOW_SQL}
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

token:
  issuer: ${TOKEN_ISSUER}
  secret: ${TOKEN_SECRET}
  expiration:
    access: ${TOKEN_ACCESS_EXPIRATION}
    refresh: ${TOKEN_REFRESH_EXPIRATION}

openai:
  api-keys: ${OPENAI_API_KEYS}

management:
  endpoints:
    web:
      exposure:
        include: health

server:
  address: 10.10.6.55
